### ISSUE TITLE
Creation of the appservice

### ISSUE THREAD

**Issue by ghost** [TurBoss/matrix-spring-appservice#3]
Hi, what would be the purpose of this repo? I would like to make an appservice and maybe on the way I will take the one you made as an example.

**Comment by TurBoss** [comment]
hello,

this is running for the spring rts engine springrts.com

its bridging some game lobby rooms to matrix
thanks for the interest

[# ](https://matrix.to/#/#sy:jauriarts.org)

**Comment by TurBoss** [comment]
Hello, have you made any progress? I'm just curious :D

**Comment by bramenn** [comment]
Hi five, I am the same person as the previous comment, I have succeeded, you already believe that an application service uses mautrix-python completely. Now I am creating a bridge. https://github.com/bramenn/gupshup
